// lib/mock-data.ts

import type { CourseWithDetails } from '@/types/courses';

const LONG_COMPANY_STRING = "ISO Safety, ASHR Construction, Mond Corp., Safety Culture";

const BASE_MOCK_COURSES: CourseWithDetails[] = [
  {
    id: 151,
    name: "Project Management Workshop",
    is_paid: false,
    price: null,
    totalUnits: 2,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2023-10-15T10:00:00Z'),
    description: "Learn the fundamentals of project management.",
    enrollmentValidityDays: 365,
    completionValidityDays: null,
  },
  {
    id: 152,
    name: "Leadership Development Program",
    is_paid: false,
    price: null,
    totalUnits: 3,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2023-11-20T14:30:00Z'),
    description: "Develop essential leadership skills.",
    enrollmentValidityDays: null,
    completionValidityDays: 365,
  },
  {
    id: 153,
    name: "Data Analytics Bootcamp",
    is_paid: false,
    price: null,
    totalUnits: 4,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-01-05T09:15:00Z'),
    description: "Intensive course on data analysis tools.",
    enrollmentValidityDays: 180,
    completionValidityDays: null,
  },
  {
    id: 154,
    name: "Project Management Essentials",
    is_paid: false,
    price: null,
    totalUnits: 5,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-01-10T11:00:00Z'),
    description: "Core concepts for managing projects effectively.",
    enrollmentValidityDays: null,
    completionValidityDays: null,
  },
  {
    id: 155,
    name: "Effective Communication Skills",
    is_paid: false,
    price: null,
    totalUnits: 2,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-02-01T13:45:00Z'),
    description: "Improve your verbal and written communication.",
    enrollmentValidityDays: 365,
    completionValidityDays: 730,
  },
  {
    id: 156,
    name: "Time Management Techniques",
    is_paid: false,
    price: null,
    totalUnits: 1,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-02-15T08:30:00Z'),
    description: "Master your schedule and increase productivity.",
    enrollmentValidityDays: null,
    completionValidityDays: null,
  },
  {
    id: 157,
    name: "Team Building Activities",
    is_paid: false,
    price: null,
    totalUnits: 6,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-03-01T15:20:00Z'),
    description: "Strategies for building cohesive teams.",
    enrollmentValidityDays: 90,
    completionValidityDays: null,
  },
  {
    id: 158,
    name: "Customer Service Excellence",
    is_paid: false,
    price: null,
    totalUnits: 2,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-03-10T10:10:00Z'),
    description: "Delivering outstanding customer experiences.",
    enrollmentValidityDays: 365,
    completionValidityDays: 365,
  },
  {
    id: 159,
    name: "Conflict Resolution Strategies",
    is_paid: false,
    price: null,
    totalUnits: 3,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-03-20T16:00:00Z'),
    description: "Methods for resolving workplace conflicts.",
    enrollmentValidityDays: null,
    completionValidityDays: null,
  },
  {
    id: 160,
    name: "Sales Fundamentals Training",
    is_paid: false,
    price: null,
    totalUnits: 7,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date('2024-04-05T09:00:00Z'),
    description: "Basic principles of successful selling.",
    enrollmentValidityDays: 180,
    completionValidityDays: 365,
  }
];

const ADDITIONAL_COURSE_NAMES = [
  'Workplace Health and Safety Basics',
  'Manual Handling Awareness',
  'Emergency Response Planning',
  'Fire Warden Training',
  'Hazard Identification Workshop',
  'Incident Reporting Fundamentals',
  'Risk Assessment Essentials',
  'Construction Site Induction',
  'Electrical Safety Awareness',
  'Confined Space Awareness',
  'Working at Heights Basics',
  'PPE Selection and Use',
  'Chemical Handling Awareness',
  'Safety Leadership for Supervisors',
  'Mental Health First Response',
  'Fatigue Management Training',
  'Ergonomics for Office Teams',
  'Noise Exposure Awareness',
  'Traffic Management Basics',
  'Forklift Safety Refresher',
  'Machine Guarding Essentials',
  'Lockout Tagout Awareness',
  'Environmental Compliance Basics',
  'Quality Control Fundamentals',
  'Document Control Essentials',
  'Workplace Bullying Prevention',
  'Diversity and Inclusion Awareness',
  'Privacy and Data Protection',
  'Cybersecurity Awareness',
  'First Aid Refresher',
  'Site Supervisor Essentials',
  'Contractor Safety Management',
  'Toolbox Talk Facilitation',
  'Return to Work Coordination',
  'Drug and Alcohol Awareness',
  'Asbestos Awareness',
  'Silica Dust Awareness',
  'Hot Work Permit Basics',
  'Permit to Work Essentials',
  'Ladder Safety Awareness',
  'Vehicle Pre-start Checks',
  'Warehouse Safety Basics',
  'Food Safety Handling',
  'Customer Complaint Handling',
  'Professional Email Etiquette',
  'Change Management Foundations',
  'Performance Coaching Basics',
  'Recruitment Interview Skills',
  'Financial Literacy for Teams',
  'Business Writing Essentials',
];

export const MOCK_COURSES: CourseWithDetails[] = [
  ...BASE_MOCK_COURSES,
  ...ADDITIONAL_COURSE_NAMES.map((name, index) => ({
    id: 161 + index,
    name,
    is_paid: false,
    price: null,
    totalUnits: (index % 8) + 1,
    companyCount: 4,
    assignedCompanies: LONG_COMPANY_STRING,
    updatedAt: new Date(
      Date.UTC(2024, 4 + (index % 6), 1 + (index % 26), 9 + (index % 8), 0, 0)
    ),
    description: `${name} mock course for table pagination testing.`,
    enrollmentValidityDays: index % 3 === 0 ? 365 : null,
    completionValidityDays: index % 4 === 0 ? 365 : null,
  })),
];
